### ISSUE TITLE
Настройки build.gradle файлов и AndroidManifest.xml.

### ISSUE THREAD

**Issue by GabovAleksander** [GabovAleksander/practicum-android-diploma#1]
Настройки build.gradle файлов и AndroidManifest.xml. Все основные настройки проекта лучше произвести заранее: минимально поддерживаемая версия Android, ориентация экрана приложения, ссылка на класс Application и основную тему, список всех библиотек, от которых зависит приложение (Retrofit, Room, Glide и т.д.).

**Comment by serj1n1o** [comment]
оценка времени выполнения - 1 час

**Comment by serj1n1o** [comment]
фактическое время выполнения 1 час 30 мин
